# Generated by Django 5.1.2 on 2025-01-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_userprofile_active_userprofile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batchName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
