# Generated by Django 5.1.2 on 2025-05-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_batch_batchname'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='batch_teachers', to='db.teacher'),
        ),
    ]
