# Generated by Django 5.1.2 on 2025-05-24 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_batch_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sessionName', models.CharField(max_length=50, unique=True)),
                ('startDateTime', models.DateTimeField(verbose_name='Start Date Time')),
                ('endDateTime', models.DateTimeField(verbose_name='End Date Time')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='db.batch')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to='db.teacher')),
            ],
        ),
    ]
