# Generated by Django 5.1.2 on 2025-05-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='faceEncoding',
            field=models.BinaryField(blank=True, null=True, verbose_name='Face Encoding'),
        ),
    ]
