# Generated by Django 5.1.2 on 2025-05-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_studentdata_faceencoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sessionName',
            field=models.CharField(max_length=50),
        ),
    ]
