# Generated by Django 5.1.2 on 2025-06-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_session_sessionname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='profilePic',
            field=models.TextField(blank=True, null=True, verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profilePic',
            field=models.TextField(blank=True, null=True, verbose_name='Profile Picture'),
        ),
    ]
