# Generated by Django 5.1.2 on 2024-10-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=30, verbose_name='Student Name')),
                ('studentID', models.IntegerField(max_length=10, verbose_name='Student Unique Identifier')),
                ('studentPassword', models.CharField(max_length=30, verbose_name='Student account password')),
            ],
        ),
    ]
