# Generated by Django 5.1.2 on 2025-01-02 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batchName', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('batchStatus', models.BooleanField(default=True, verbose_name='Batch Status')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('hireDate', models.DateField(verbose_name='Hire Date')),
                ('contactNo', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('teacherPassword', models.CharField(max_length=100, verbose_name='Teacher Password')),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture')),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=30, verbose_name='Student Name')),
                ('admissionNo', models.IntegerField(unique=True, verbose_name='Admission Number')),
                ('rollNo', models.IntegerField(verbose_name='Roll Number')),
                ('studentClass', models.CharField(max_length=10, verbose_name='Class')),
                ('division', models.CharField(max_length=10, verbose_name='Division')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('fatherName', models.CharField(max_length=30, verbose_name="Father's Name")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('contactNo', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('joinedDate', models.DateField(verbose_name='Joined Date')),
                ('accountStatus', models.BooleanField(default=True, verbose_name='Account Status')),
                ('studentPassword', models.CharField(max_length=30, verbose_name='Student account password')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='batchIncharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='api.teacher'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10, verbose_name='Role')),
                ('dbUniqueID', models.IntegerField(verbose_name='database Unique ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
