# Generated by Django 5.1.2 on 2024-12-17 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('hireDate', models.DateField(verbose_name='Hire Date')),
                ('contactNo', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='batchIncharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='api.teacher'),
        ),
    ]
