# Generated by Django 5.1.2 on 2024-10-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
