# Generated by Django 5.1.2 on 2024-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studentdata_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='studentClass',
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
    ]
