# Generated by Django 5.1.2 on 2025-01-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacherPassword',
            field=models.CharField(default='default_password', max_length=100, verbose_name='Teacher Password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
