# Generated by Django 5.1.2 on 2024-10-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_attendance_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminAccess',
            new_name='AdminData',
        ),
    ]
