# Generated by Django 5.1.2 on 2024-10-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studentdata_studentclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='studentClass',
        ),
    ]
