# Generated by Django 5.1.2 on 2024-11-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_studentdata_studentclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('students', models.ManyToManyField(related_name='batches', to='api.studentdata')),
            ],
        ),
    ]
