# Generated by Django 5.1.2 on 2025-01-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teacher_teacherpassword_alter_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dbUniqueID',
            field=models.IntegerField(default=1, verbose_name='database Unique ID'),
            preserve_default=False,
        ),
    ]
