# Generated by Django 5.1.2 on 2024-12-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='studentID',
            field=models.IntegerField(unique=True, verbose_name='Student Unique Identifier'),
        ),
    ]
