# Generated by Django 5.1.2 on 2024-12-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_studentdata_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='students',
        ),
        migrations.AddField(
            model_name='batch',
            name='active_batch',
            field=models.BooleanField(default=True, verbose_name='Is the batch active'),
        ),
        migrations.AddField(
            model_name='batch',
            name='seat_number',
            field=models.IntegerField(default=0, verbose_name='Number of seats available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdata',
            name='studentBatch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdata',
            name='studentPFP',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Student Profile Picture'),
        ),
    ]
