# Generated by Django 5.1.2 on 2024-12-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_batch_name_remove_batch_students_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='active_batch',
            new_name='activeBatch',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='seat_number',
            new_name='seatNumber',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='parentName',
            field=models.CharField(default='Blank Name', max_length=30, verbose_name='Parent Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdata',
            name='phoneNumber',
            field=models.IntegerField(default=0, verbose_name='Parent Phone Number'),
            preserve_default=False,
        ),
    ]
